export const actionTypes = {
    CHANGE_ROUTE: 'CHANGE_ROUTE'
};

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const FETCH_SESSION_USER_SUCCESS = 'FETCH_SESSION_USER_SUCCESS';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
